### ISSUE TITLE
Add a warning?

### ISSUE THREAD

**Issue by sudo-suhas** [feross/TheAnnoyingSite.com#1]
I guess I should know better than to open the website with a very honest name but I did it anyway. Instant regret 😅. Maybe add a warning to the readme and suggest opening in incognito mode?

**Comment by kocoten1992** [comment]
yes and I regret holding space for 3s, 1 is enough to kill my pc =((

**Comment by jarrodconnolly** [comment]
so much regret.

**Comment by mccoderpy** [comment]
I opened it and the  child's pop up, but on the end only 2 pictures was downloaded and nothing else 😂
